### PR TITLE
DBZ-6581 Add exchange parameter to RabbitMQ consumer

### PR DESCRIPTION
**Pull request by starxg**
Hi,

I added an exchange parameter to RabbitMq Stream Consumer, which can quickly and conveniently specify RabbitMq exchange. 

like this
```properties
debezium.sink.rabbitmq.exchange=test_exchange
```

### CODE REVIEW

**Comment by jpechane** [comment]
@starxg Hi, could you please create a Jira issue with the feature request, and link it here?

**Comment by ibnubay** [comment]
Hi @jpechane and @starxg , may be we can using my PR in [https://github.com/debezium/debezium-server/pull/29](url).
For more complete changes (including @starxg needs)

**Comment by starxg** [comment]
> @starxg Hi, could you please create a Jira issue with the feature request, and link it here?

I created an issue.
https://issues.redhat.com/browse/DBZ-6581

**Comment by jpechane** [comment]
@starxg Thank you for the PR. I re-purposed the Jira for https://github.com/debezium/debezium-server/pull/30

Let's continue discussion there

**Pull request closed without merging**
