### PR TITLE
DBZ-8367: fix error message: show the correct config-path & format

### PR DESCRIPTION
**Pull request by paumr**
When launching debezium-server via:
``` bash
java -jar ./debezium-server-dist/target/debezium-server-dist-3.0.0-SNAPSHOT-runner.jar io.debezium.server.Main
```

it errors out with the log-line:
```
Failed to load mandatory config value 'debezium.sink.type'. Please check you have a correct Debezium server config in /<redacted>/debezium/debezium-server/conf/application.properties or required properties are defined via system or environment variables.
```

This is broken in two ways:
- the printed path is wrong. quarkus loads application.properties from the `config` directory: https://quarkus.io/guides/config-reference
- the error message is logged via println. LOGGER should be used instead (otherwise depending on the logging-setup the message might be dropped - due to not being json)

This PR fixes both of these issues.

### CODE REVIEW

**Comment by Naros** [comment]
Hi @paumr, can you please raise a Jira issue to track this change and update the PR commit messages to be prepended with the Jira issue key?

**Comment by jpechane** [comment]
Hi, IIRC the `System.err` was used intentionally to make sure the error is printed even in case of logging misconfiguration.

**Comment by paumr** [comment]
> Hi, IIRC the `System.err` was used intentionally to make sure the error is printed even in case of logging misconfiguration.

Hi, thanks for the information!
Maybe it would make sense to print the error both ways? That way we the message will never be dropped.

**Comment by jpechane** [comment]
@paumr Makes sense

**Comment by paumr** [comment]
As requested I:
- created a jira issue
- prepended all commits with it's ID (and the PR)
- modified the error message to print to stderr and LOGGER

**Comment by jpechane** [comment]
@paumr Applied, thanks

**Pull request merged**
