### PR TITLE
[ci] Ignore disk space limits

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by vjuranek** [comment]
I've already created https://issues.redhat.com/browse/DBZ-7528 for it.

**Comment by jpechane** [comment]
@vjuranek Thanks for the info, closing it then.

**Comment by vjuranek** [comment]
@jpechane this wasn't meant to close this PR, just info that I already created a Jira for it which should be closed byt this PR. Sorry for misunderstanding, reopening.

**Comment by jpechane** [comment]
Closing now as it seems the issue is no longer present

**Pull request closed without merging**
