### PR TITLE
DBZ-7214 AWS SQS as sink type

### PR DESCRIPTION
**Pull request by koneru9999**
https://issues.redhat.com/browse/DBZ-7214

The implementation mostly is a clone of existing `kinesis` sink.

### CODE REVIEW

**Comment by jpechane** [comment]
@koneru9999 Thanks for the PR! Would you be willing to develop it a bit more if possible? Since Kinesis came TestContainers (https://java.testcontainers.org/modules/localstack/) with localstack support were made available. We use test containers in other tests like `RocketMqIT`. Would you be willing to try and rewrite the test to not run against AWS but against the local container so it ould be executed as standard part of CI? If it is something that is technically viable then we might retorfit Kinesis test to use it too.
WDYT?

**Comment by koneru9999** [comment]
@jpechane This PR has now been adjusted to use `localstack` module from `Testcontainers`. I have not modified the existing `kinesis` tests as they are beyond the scope of this PR IMHO.

**Comment by jpechane** [comment]
@koneru9999 LGTM. I triggerd the CI and if it passes could you please suqsh the commits into a single one and remove the merge commit? The final commit message should start with `DBZ-7214 `. Thanks

**Comment by koneru9999** [comment]
> @koneru9999 LGTM. I triggerd the CI and if it passes could you please suqsh the commits into a single one and remove the merge commit? The final commit message should start with `DBZ-7214 `. Thanks

@jpechane I have now squashed the commits into a single commit even though the [build failed on CI](https://github.com/debezium/debezium-server/actions/runs/7152898412/job/19549529459) but on the other modules. Please have a final look.

**Comment by jpechane** [comment]
@koneru9999 Merged via https://github.com/debezium/debezium-server/pull/59, thanks a lot!
Could you please sheare your name so I can add you to the list of contributors?
Also could you please prepare a PR with documentation?

**Pull request closed without merging**
