### PR TITLE
[DBZ-7909] RabbitMQ Native Stream: Making sure RequestedFrameMax get sent to StreamClient

### PR DESCRIPTION
**Pull request by zikphil**
This fixes an issue I was having where I was setting the frame_max variable on the connection configuration but it was not propagating to the StreamClient. This patch fixes this issue.

https://issues.redhat.com/browse/DBZ-7909

### CODE REVIEW

**Comment by jpechane** [comment]
@zikphil Could you please change the commit message as it refers to DBZ-8201 instead of DBZ-7909

**Comment by jpechane** [comment]
@zikphil LGTM, would it be possible to add the remaining config options of the `EnvironmentBuilder`?

**Comment by zikphil** [comment]
> @zikphil LGTM, would it be possible to add the remaining config options of the `EnvironmentBuilder`?

@jpechane This is the part that is a bit unclear to be. **I do not code Java** but it appears to me that the ConnectionFactory is not used at all by the rabbitmq-stream-client so I am not sure why this is part of the debezium-server documentation and used in the class itself. Perhaps it is by convenience just to get validation on the host/port/virtualHost etc... but none of the wildcard will end up being used by the EnvironmentBuilder unless coded in.

I added a new commit that removes the usage of the ConnectionFactory and instead uses the variables documented here: [https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#configuring-the-environment](https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#configuring-the-environment)

I've also added some config for the StreamProducer defined here: [https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#producer](https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#producer)

It is a bigger change, perhaps we could squeeze it in for 3.0 Beta. If you accept this I can also put a PR for the documentation to be updated.

**Comment by jpechane** [comment]
@zikphil Hi, I am sorry for the late reply. I think the PR is good. I'd just keep the old property names for host/port (with connection prefix), makr them as deprecate and emit a warning when used. They'd  be removed later. The docs update will reflect the new names and new config options. WDYT?

**Pull request closed without merging**
