### PR TITLE
Dbz 6638 multiple cassandra versions

### PR DESCRIPTION
**Pull request by eizners**

### CODE REVIEW

**Comment by jpechane** [comment]
@eizners Cassandra 3 contains 250 MB of deps, v4 and DSE looks correct

**Comment by jpechane** [comment]
@eizners This should be done, please review the change and test it.
The usage is like
`env EXTRA_CONNECTOR=cassandra-3 ./run.sh` or `env EXTRA_CONNECTOR=dse ./run.sh`
The package file is now clean with only few duplicate files present

**Comment by eizners** [comment]
Made fixes and tested DSE and Cassandra4.

**Comment by jpechane** [comment]
@eizners Removed merge commit and applied, thanks for the good job!

**Comment by jpechane** [comment]
We just need to update Debezium Server docs.

**Pull request merged**
